### PR TITLE
handle_receive_pong should return true on success

### PR DESCRIPTION
**Pull request by JasonCoombs**
The problems discussed in https://github.com/libbitcoin/libbitcoin-node/issues/396 have prevented libbitcoin from receiving pong messages. We may never have received a pong message, ever, because of the bugs impacting message queue processing and inbound/outbound timeouts. There will be systemic consequences to fixing these problems, as the entire network behavior of libbitcoin is changed when channels are allowed to stay open until actual errors or real timeouts are detected.

### CODE REVIEW

**Comment by JasonCoombs** [comment]
> It’s not clear what “proposed fixes” you are referring to.

When the PR is submitted you will see them.

**Comment by JasonCoombs** [comment]
> As previously pointed out, the peer timeout is configurable, so no such vulnerability.

Still not sure why you keep saying that this is all functioning as-designed, as-intended. There are numerous aspects which do not conform to the original expectations and design rationale of BIPs and Bitcoin Core modifications from the last eight years. There certainly is some value in keeping channels open for short periods of time rather than allowing them to persist, particularly if closing them disconnects from a slow peer and replaces it with a fast one. But there are only a few thousand peers available at any moment, and the policy of constantly disconnecting from them even if they are performing well isn't helpful. I noticed that in v3 the default channel lifetime was only 60 minutes.

https://github.com/libbitcoin/libbitcoin-node/blob/version3/data/bn.cfg#L57

Are you aware that libbitcoin is sending getdata messages containing the maximum inventory size of 50,000 hashes without first requesting from the peer the list of the peer's inventory? This is an example of not following the design rule of every other Bitcoin node, and the decision to do it differently seems to be connected to the attempt to build a BOOST ASIO Proactor-only mode of operation that never retains any state information between what are supposed to be related messages. I don't think that's correct, even if it can be made to work if your timeouts are small.

https://pdfs.semanticscholar.org/8389/de4255f305333a7126238008548eae2a67ae.pdf#page=5

On my slow iMac without SSD what we get from a getdata request containing 50,000 hashes is an impossible-to-process-before-timeout response from the peer, then we disconnect after receiving a small fraction of the requested blocks, and we repeat. This is wasting resources, sending messages to the peers that we know are unduly burdensome to them and that are never going to be useful to us. I wanted this fixed, so I fixed it. When the PR is submitted you're free to ignore it.

**Comment by evoskuil** [comment]
You seem to be confusing implementation details with protocol. I know it is functioning as designed, because I designed it. The implementation confirms with protocol. You have not shown otherwise.

Your original issue with libbitcoin was that we were not implementing ASIO calls correctly. You seem to have switched to a concern that we implement the network protocol differently than the Satoshi prototype.

As I pointed out, the network protocol is not stateful across sub-protocols. There is no requirement to process messages across sub-protocols in order. The statefulness is sub-protocols is clearly implemented in the protocol classes.

**Comment by JasonCoombs** [comment]
Here's the PR: https://github.com/libbitcoin/libbitcoin-network/pull/239

**Comment by JasonCoombs** [comment]
> Your original issue with libbitcoin was that we were not implementing ASIO calls correctly. You seem to have switched to a concern that we implement the network protocol differently than the Satoshi prototype.

I did not have an "original issue with libbitcoin" as you assert. I was trying to understand how it was designed, and why, without the benefit of the ordinary amount of discussion between developers that literally every other open source project I have ever seen contains in the repos and in comment form in the code. Instead of appreciating my efforts to contribute, instead of viewing my confusion and misunderstandings, conveyed in good faith in my questions and comments, as a tool for you to better understand what needs to be improved for developer education, you just get offended and react as though you are being attacked personally.

Your bizarre confrontational style of communication is over the top. I am not going to try to contribute further to this project. If you want to use my improvements to libbitcoin in the future you will have access to them in my public repository when it is made available. Pull whatever you like and ignore whatever you don't.

**Comment by evoskuil** [comment]
I am referring specifically to the first issue you raised, adamantly telling us that we’re were not properly implementing ASIO. You were rejecting inputs that you were given, despite my best efforts. I don’t get offended, I get annoyed at wasting my time when someone who does not know the code continues to tell us we have it wrong, after being shown otherwise several times. Your refusal to listen is not contribution, it’s distraction. You are free to fork the code under the license and make whatever changes you want.

**Comment by JasonCoombs** [comment]
You haven't implemented ASIO correctly. Rather than working through the complicated problems that resulted from this fact, you adamantly tell me that it is working as designed. There are many moving parts, including things like your randomizing of timeouts, which obscure from your view the fact that things aren't working the way you think they're working. My original debugging work was very difficult and time-consuming as I became oriented on where the problems are, and the fact that I have been successfully fixing these problems should cause you to question if not retract your previous remarks. I'm not going to spend my time arguing with you. When you see how my fork has changed and improved upon your starting point, you can do the work to pull my improvements if you value them.

**Comment by evoskuil** [comment]
Yet you have yet to demonstrate any behavior that was not intended or explained to you before you “fixed” it. More interestingly, you have not demonstrated a single case where ASIO is used incorrectly, instead focusing on questions of high level protocol interpretation. Please stop spamming our issues board with promises to demonstrate such things. If you can identify an error in ASIO implementation, please do so, I’d be happy to see it. Otherwise you are indeed wasting you time, and ours.

**Pull request closed without merging**
